# Generated by Django 4.2.4 on 2023-10-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightname', models.CharField(blank=True, max_length=50, null=True)),
                ('flightnumber', models.IntegerField(blank=True, null=True)),
                ('pioletname', models.CharField(blank=True, max_length=50, null=True)),
                ('copioletname', models.CharField(blank=True, max_length=50, null=True)),
                ('totalseat', models.IntegerField(blank=True, null=True)),
                ('economyseat', models.IntegerField(blank=True, null=True)),
                ('busnissseat', models.IntegerField(blank=True, null=True)),
                ('firstclassseat', models.IntegerField(blank=True, null=True)),
                ('economyprice', models.IntegerField(blank=True, null=True)),
                ('busnissprice', models.IntegerField(blank=True, null=True)),
                ('firstclassprice', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Flight_image')),
            ],
        ),
    ]
