# Generated by Django 4.2.4 on 2023-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourpackagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourname', models.CharField(blank=True, max_length=25, null=True)),
                ('tourprice', models.IntegerField(blank=True, null=True)),
                ('tourduration', models.CharField(blank=True, max_length=50, null=True)),
                ('tourdescription', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='TourPackage_image')),
            ],
        ),
    ]
