# Generated by Django 4.2.4 on 2023-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_tourpackagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelexploredb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explorename', models.CharField(blank=True, max_length=100, null=True)),
                ('exploredescription', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='explore_image')),
            ],
        ),
    ]
