# Generated by Django 4.2.4 on 2023-11-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_hotelexploredb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelroomcatagorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomcatagory', models.CharField(blank=True, max_length=50, null=True)),
                ('roomcatdescription', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Hotelcat_image')),
            ],
        ),
    ]
