# Generated by Django 4.2.4 on 2023-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_roomdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdb',
            name='fromplace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flightdb',
            name='toplace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
