# Generated by Django 4.2.4 on 2023-11-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_checkoutflightdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutflightdb',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
