# Generated by Django 4.2.4 on 2023-11-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_checkoutflightdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutflightdb',
            name='datefrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutflightdb',
            name='dateto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
