# Generated by Django 4.2.4 on 2023-11-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_alter_checkoutflightdb_datefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutflightdb',
            name='datefrom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutflightdb',
            name='dateto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
