# Generated by Django 4.2.4 on 2023-11-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_ratingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdb',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
