# Generated by Django 4.2.4 on 2023-11-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_alter_ratingdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourReplydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touremail', models.CharField(blank=True, max_length=20, null=True)),
                ('tourplace', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('tourmessage', models.CharField(blank=True, max_length=20, null=True)),
                ('tourprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
