# Generated by Django 4.2.4 on 2023-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_tourreplydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='roombookeddb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelcustomername', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('hotelcustomeremail', models.CharField(blank=True, max_length=30, null=True)),
                ('hotelcustomermobile', models.IntegerField(blank=True, null=True)),
                ('hotelbookingstartdate', models.CharField(blank=True, max_length=30, null=True)),
                ('hotelbookingenddate', models.CharField(blank=True, max_length=30, null=True)),
                ('hotelprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
